models/models.py
from mongoengine import Document, StringField, EmbeddedDocument, ListField, EmbeddedDocumentField

class Location(EmbeddedDocument):
    location = StringField(required=True)
    department = StringField()
    status = StringField()

class Agency(EmbeddedDocument):
    agency = StringField(required=True)
    locations = ListField(EmbeddedDocumentField(Location))
    department = StringField()
    status = StringField()

class Client(Document):
    client = StringField(required=True)
    agencies = ListField(EmbeddedDocumentField(Agency))

app.py
from flask import Flask
from flask_pymongo import PyMongo
from pymongo import MongoClient

app = Flask(__name__, static_url_path='/static')
app.secret_key = 'RizeMonitoring'

# Set the MONGO_URI in the Flask configuration
app.config["MONGO_URI"] = "mongodb+srv://admin:admin123@zuitt.sknrqtl.mongodb.net/rize.accounts?retryWrites=true&w=majority"

# Initialize PyMongo with the Flask app
mongo = PyMongo(app)

# Access the 'rize' database (this will create it if it doesn't exist)
db = mongo.db

# Access the 'accounts' collection (this will create it if it doesn't exist)
collection = db["accounts"]

@app.teardown_appcontext
def close_mongo_client(error):
    mongo.cx.close()

if __name__ == "__main__":
    app.run(debug=True)

routes/__init__.py
from .index import index_bp
from .add_data import add_data_bp
from .delete_data import delete_data_bp
from .retrieve_data import retrieve_data_bp

routes/add_data.py
from flask import Blueprint, request, redirect, url_for, flash
from models.models import Client, Agency, Location

add_data_bp = Blueprint('add_data', __name__)

@add_data_bp.route("/add_data", methods=["POST"])
def add_data():
    try:
        client_name = request.form["client"]
        agency_name = request.form["agency"]
        location_name = request.form.get("location")
        department_name = request.form.get("department")
        status = request.form["status"]

        active = 1 if status == "active" else 0

        client = Client.objects(client=client_name).first() or Client(client=client_name)
        agency = next((a for a in client.agencies if a.agency == agency_name), None) or Agency(agency=agency_name)

        if location_name:
            location = Location(location=location_name, department=department_name, active=active)
            agency.locations.append(location)

        client.agencies.append(agency)
        client.save()

        flash("Data added successfully", "success")
    except Exception as e:
        flash(f"Error adding data: {str(e)}", "error")

    return redirect(url_for("index"))

# Register the blueprint within the same file
from . import app  # Import app from the current package
app.app.register_blueprint(add_data_bp)

routes/delete_data.py
from flask import Blueprint, request, redirect, url_for, flash
from models.models import Client

delete_data_bp = Blueprint('delete_data', __name__)

@delete_data_bp.route("/delete_data", methods=["POST"])
def delete_data():
    try:
        client_name = request.form.get("client")
        agency_name = request.form.get("agency")
        location_name = request.form.get("location")

        if not (client_name or agency_name or location_name):
            flash("At least one of Client, Agency, or Location is required for deletion", "warning")
            return redirect(url_for("index"))

        query = {}
        if client_name:
            query["client"] = client_name
        if agency_name:
            query["agencies.agency"] = agency_name
        if location_name:
            query["agencies.locations.location"] = location_name

        deleted_count = Client.objects(**query).delete()

        if deleted_count > 0:
            flash("Data deleted successfully", "success")
        else:
            flash("No matching data found for deletion", "info")
    except Exception as e:
        flash(f"Error deleting data: {str(e)}", "error")

    return redirect(url_for("index"))

# Register the blueprint within the same file
from . import app  # Import app from the current package
app.app.register_blueprint(delete_data_bp)

routes/index.py
from flask import Blueprint, render_template
from app import mongo

index_bp = Blueprint('index', __name__)

@index_bp.route("/")
def index():
    try:
        data = mongo.db.clients.find()
        counts = {
            "client_count": sum(1 for client in data),
            "agency_count": sum(len(client.get("agencies", [])) for client in data),
            "location_count": sum(len(agency.get("locations", [])) for client in data for agency in client.get("agencies", []))
        }
        return render_template("index.html", data=data, counts=counts)
    except Exception as e:
        error_message = f"Error accessing MongoDB: {str(e)}"
        print(error_message)  # Add this line for debugging
        return error_message

# Register the blueprint within the same file
from . import app  # Import app from the current package
app.app.register_blueprint(index_bp)

routes/retrieve_data.py
from flask import Blueprint, request, jsonify
from models.models import Client

retrieve_data_bp = Blueprint('retrieve_data', __name__)

@retrieve_data_bp.route("/retrieve_data", methods=["GET"])
def retrieve_data():
    client_name = request.args.get("client")
    agency_name = request.args.get("agency")
    location_name = request.args.get("location")

    query = {}

    if client_name:
        query["client"] = client_name

    if agency_name or location_name:
        query["$or"] = [{"agencies.agency": agency_name}, {"agencies.locations.location": location_name}]

    retrieved_data = Client.objects(**query)

    retrieved_data = [item.to_mongo().to_dict() for item in retrieved_data]

    return jsonify(retrieved_data)

# Register the blueprint within the same file
from . import app  # Import app from the current package
app.app.register_blueprint(retrieve_data_bp)

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Client Data</title>
    <script src="{{ url_for('static', filename='scripts.js') }}"></script>

</head>
<body>
    <h1>Client Data</h1>
    <form action="{{ url_for('add_data.add_data') }}" method="post" onsubmit="return showSuccessAlert();">
        <label for="add_client">Client:</label>
        <input type="text" id="add_client" name="client" required><br>
        
        <label for="add_agency">Agency:</label>
        <input type="text" id="add_agency" name="agency" required><br>
        
        <label for="add_location">Location:</label>
        <input type="text" id="add_location" name="location"><br>
        
        <label for="department">Department:</label>
        <input type="radio" name="department" id="rize" value="rize" required> Rize
        <input type="radio" name="department" id="grade-us" value="grade-us" required> Grade.us
        <input type="radio" name="department" id="white-label" value="white-label" required> White Label<br>
        
        <label for="status">Status:</label>
        <input type="radio" name="status" id="trial" value="trial" required> Trial
        <input type="radio" name="status" id="active" value="active" required> Active<br>
        
        <button type="submit">Add Data</button>
    </form>

    <form action="{{ url_for('delete_data.delete_data') }}" method="post" onsubmit="return showDeleteAlert();">
        <!-- Add input fields for Client, Agency, and Location as needed -->
        <label for="delete_client">Client:</label>
        <input type="text" id="delete_client" name="client">
        
        <label for="delete_agency">Agency:</label>
        <input type="text" id="delete_agency" name="agency">
        
        <label for="delete_location">Location:</label>
        <input type="text" id="delete_location" name="location">
    
        <button type="submit">Delete Data</button>
    </form>    
    
    <p>Total Clients: {{ counts.client_count }}</p>
    <p>Total Agencies: {{ counts.agency_count }}</p>
    <p>Total Locations: {{ counts.location_count }}</p>

    <!-- Form for retrieving data -->
    <form onsubmit="return false;">
        <label for="retrieve_client">Client:</label>
        <input type="text" id="retrieve_client" name="client">
        
        <label for="retrieve_agency">Agency:</label>
        <input type="text" id="retrieve_agency" name="agency">
        
        <label for="retrieve_location">Location:</label>
        <input type="text" id="retrieve_location" name="location">
    
        <button type="button" onclick="retrieveData()">Retrieve Data</button>
    </form>    

    <!-- Display retrieved data here -->
    <h2>Retrieved Data</h2>
    <table>
        <thead>
            <tr>
                <th>Client</th>
                <th>Agency</th>
                <th>Location</th>
                <th>Department</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            
        </tbody>
    </table>

</body>
</html>